*** Variables ***
${WAIT_TIME_COMPONENT}         60s
${WAIT_TIME_PAGE}              10s
${WAIT_TIME_INSERT}            5s
${SCREENSHOT_NUMBER}           0
${URL}                         https://advantageonlineshopping.com/#/
${URL_API}                     https://www.advantageonlineshopping.com/accountservice/accountrest/api/v1
${REGISTER_URL}                /register
${HEADERS}                     {"Content-Type":"application/json","accept":"*/*"}
${DEFAULT_BROWSER}             chrome