*** Variables ***
&{home_page}
...  lbl_home=/html/body/header/nav/div/a/span[1]
...  btn_menu_buscar=//*[@id="menuSearch"]
...  input_pesquisar=//input[@id="autoComplete"]
...  lbl_laptops=//*[@id="output"]//a/label
...  div_fechar_pesquisa=//div[@data-ng-click='closeSearchForce()']
...  txt_search_result=//*[@id="searchPage"]/div[3]/div/div/div[2]/ul/li[1]/p[1]/a
...  span_laptop=//span[@id='laptopsTxt']