name: Run Robot Framework Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Instalar dependências Python
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          # ou: pip install robotframework selenium robotframework-seleniumlibrary

      - name: Configurar Chrome e ChromeDriver
        uses: browser-actions/setup-chrome@v1
        with:
          chrome-version: stable
          chromedriver-version: latest

      - name: Rodar testes com Robot Framework
        run: |
          python -m robot -d reports ./testCases

      - name: Upload de Relatórios
        uses: actions/upload-artifact@v4
        with:
          name: robot-reports
          path: reports/
