name: Run Robot Framework Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          # Caso não tenha requirements.txt, instale direto:
          # pip install robotframework selenium robotframework-seleniumlibrary

      - name: Baixar WebDriver (ChromeDriver)
        uses: browser-actions/setup-chrome@v1
        with:
          chrome-version: stable
      - run: |
          CHROMEDRIVER_VERSION=$(curl -sS chromedriver.storage.googleapis.com/LATEST_RELEASE)
          wget -q "https://chromedriver.storage.googleapis.com/$CHROMEDRIVER_VERSION/chromedriver_linux64.zip"
          unzip chromedriver_linux64.zip -d /usr/local/bin/
          rm chromedriver_linux64.zip

      - name: Rodar testes com Robot Framework
        run: |
          python -m robot -d reports ./testcases

      - name: Upload de Relatórios
        uses: actions/upload-artifact@v3
        with:
          name: robot-reports
          path: reports